# Generated by Django 4.1.6 on 2023-03-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name_plural': 'Закладка'},
        ),
    ]
